[package]
name = "noble_prost_build"
version = "0.1.0"
authors = ["Zaki Manian <zaki@iqlusion.io>"]
edition = "2024"


[dependencies]
prost = "0.7"
tonic = "0.4"
prost-build = "0.7"
tempdir = "0.3"
walkdir = "2"
tonic-build = "0.4"
regex = "1.5"
