// @generated
// This file is @generated by prost-build.
/// Module is the config object of the Halo module.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Module {
    /// denom is the denom this module is allowed to govern, burn, mint, etc.
    #[prost(string, tag = "1")]
    pub denom: ::prost::alloc::string::String,
    /// underlying is the denom this module uses as underlying collateral.
    #[prost(string, tag = "2")]
    pub underlying: ::prost::alloc::string::String,
}
impl ::prost::Name for Module {
    const NAME: &'static str = "Module";
    const PACKAGE: &'static str = "halo.module.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "halo.module.v1.Module".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/halo.module.v1.Module".into()
    }
}
include!("halo.module.v1.serde.rs");
// @@protoc_insertion_point(module)
