// @generated
// This file is @generated by prost-build.
/// Module is the config object of the Noble Dollar module.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Module {
    /// denom defines the smallest denomination of the Noble Dollar.
    /// This is configurable in case we want different denominations on testnet and mainnet.
    #[prost(string, tag = "1")]
    pub denom: ::prost::alloc::string::String,
    /// authority defines the custom module authority.
    #[prost(string, tag = "2")]
    pub authority: ::prost::alloc::string::String,
    /// vaults_minimum_lock defines the minimum required amount to lock into a Noble Dollar Vault.
    #[prost(int64, tag = "3")]
    pub vaults_minimum_lock: i64,
    /// vaults_minimum_unlock defines the minimum required amount to unlock from a Noble Dollar Vault.
    #[prost(int64, tag = "4")]
    pub vaults_minimum_unlock: i64,
}
impl ::prost::Name for Module {
    const NAME: &'static str = "Module";
    const PACKAGE: &'static str = "noble.dollar.module.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "noble.dollar.module.v1.Module".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/noble.dollar.module.v1.Module".into()
    }
}
include!("noble.dollar.module.v1.serde.rs");
// @@protoc_insertion_point(module)
